name: faker_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_hotreload: ^1.1.0
  alfred: ^0.1.5+3
  faker_dart: ^0.1.4
  brazillian: ^2.0.0
  intl: ^0.17.0

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
